-- HISTORICAL ONLY — DO NOT EXECUTE.
--
-- Proposal follow-up is scheduled exclusively in vercel.json. The former
-- pg_cron job duplicated that schedule and embedded an authorization secret.
-- Migration 20260802110130 removes the database job from every environment.
-- The exposed historical secret must remain revoked; never add credentials to
-- SQL files. Use the CRON_SECRET environment variable managed by Vercel.
